workflows:
  ios:
    name: Build iOS
    max_build_duration: 120
    environment:
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods
          pod repo update
          pod install --project-directory=iosApp
      - name: Build iOS
        script: |
          ./gradlew :iosApp:syncFramework -Pconfiguration=Release
      - name: Archive iOS app
        script: |
          xcodebuild -workspace iosApp/iosApp.xcworkspace \
                     -scheme iosApp \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/iosApp.xcarchive \
                     clean archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/iosApp.xcarchive \
                     -exportOptionsPlist iosApp/ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR

    artifacts:
      - iosApp/build/ios/ipa/kmmtestapp.ipa
