workflows:
  ios:
    name: Build iOS
    max_build_duration: 120
    environment:
      vars:
        XCODE_PROJECT: "kmmtestapp.xcodeproj" # <-- Put your xcode project name here
        XCODE_SCHEME: "iosApp" # <-- Put your bundle xcode scheme here
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Cocoapods installation
        script: |
          cd $CM_BUILD_DIR/iosApp
          pod install
      - name: Set up code signing settings on Xcode project
        script: |
          cd $CM_BUILD_DIR/iosApp
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          cd $CM_BUILD_DIR/iosApp
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - iosApp/build/ios/ipa/kmmtestapp.ipa
