workflows:
  ios:
    name: iOS Build
    environment:
      vars:
        kotlin_version: 2.0.0
      xcode: latest

    scripts:
      - name: Set permissions for gradlew
        script: |
          chmod +x ./gradlew
      - name: Set up environment
        script: |
          echo "sdk.dir=$HOME/Library/Android/sdk" > local.properties

      - name: Build Kotlin Multiplatform framework
        script: |
          ./gradlew :shared:packForXcode -PXCODE_CONFIGURATION=Release

      - name: Build .ipa
        script: |
          cd iosApp
          xcodebuild archive \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $HOME/build/iosApp.xcarchive

          xcodebuild -exportArchive \
            -archivePath $HOME/build/iosApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $HOME/build/iosApp

    artifacts:
      - $HOME/build/iosApp/*.ipa